### ISSUE TITLE
Adding new shows not working

### ISSUE THREAD

**Issue by loungebob** [SickRage/SickRage#4225]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/ 4b69468cc1ea330f598364718068352a54b0eb92 
OS: Win10
What you did: adding a  ew show 
What happened: spinning wheel indicating indexers are being searched keeps spinning endlessly and no search results are ever returned
What you expected: search results appearing for selection
Logs:
```
PASTE LOGS HERE
```
There are no log entries in debug mode for this issue. Trying to add a new show results in a spinning wheel without search results being supplied. This has been going on for a few days. Neither reboot nor server restart fixed this.

**Comment by roeiegans** [comment]
Same issue here. I'm on the master commit 4b69468cc1ea330f598364718068352a54b0eb92 .

**Comment by loungebob** [comment]
Tried dev branch, same issue for me. I kinda would really like to have this feature working again.

**Comment by MrSnoebel** [comment]
Same issue here, I even tried a fresh install from scratch. 

Branch:  master  
Commit:  4b69468cc1ea330f598364718068352a54b0eb92  
Version:  v2017.12.19-1  
Database Version: 44.0 
OS; Win 2016 (reported as win 10 in about.

**Comment by DrDrewZA** [comment]
Just checked this again - still no luck...  I realise that given the time of year, its likely the devs are on break - hopefully one of them pick this one up when they get back to their keyboards :)

**Comment by roeiegans** [comment]
Anyone reading this? Would be nice after an update (where you should expect some bugs) if there was some more support. I get, that many developers do this in their spare time, and I do appreciate the work very much. But if I can't support my update for over a month, maybe I wouldn't have send the update out at that specific moment.

**Comment by MrSnoebel** [comment]
As a workaround for the time being I create a tvshow.nfo with just the ID and name listed, this is enough for SR to pick up the rest of the details from TVDB.

**Comment by DrDrewZA** [comment]
MrSnoebel - can you expand on that - ie give a quick set of instructions?

Many TIA

**Comment by DrDrewZA** [comment]
As an update here - I tried to add shows through the IMDB popular shows option and finally got an error - although it is worth noting that the show was in fact added successfully regardless of the error:

File C:\SickRage\SickRage\sickbeard\show_queue.py:280, in show_name: return self.show.name if self.show else self.showDir.rsplit(os.sep)[-1] AttributeError: 'NoneType' object has no attribute 'rsplit'

**Comment by MrSnoebel** [comment]
Create the dir for the serie you want to add.
Put a file named tvshow.nfo in that folder
You need to create it like this: 

_<?xml version='1.0' encoding='UTF-8'?>
<tvshow>
  <title>showname</title>
  <rating />
  <year />
  <plot />
  <id>the ID of the series</id>
  <genre />
  <premiered />
  <studio />
</tvshow>_

The ID you van find in the URL when you manually look up the serie on the TVDB site.

After this you can add the show in SR as an exiting folder, SR recognises the file and adds the serie.

**Comment by roeiegans** [comment]
THX, that works for me as a workaround. Still hope for a permanent solution however.

**Comment by miigotu** [comment]
Duplicate of #4224

**Comment by loungebob** [comment]
@miigotu even with the changes you made in the newest commit, this did not solve my issue. my issue is still that I cannot add new shows through "add shows" because there is never any search results supplied and the spinning wheel goes on forever.

**Comment by roeiegans** [comment]
Same here

**Comment by MrSnoebel** [comment]
Updated master to the lastest version, indeed, still the same problem.

**Comment by DrDrewZA** [comment]
hmmm - perhaps the problem actually lies with thetvdb.com and not sickrage itself? I get a http 503 error (service unavailable) if I try to browse their site and I read somewhere they've just completed a rewrite of their code...  coincidence?

**Comment by DrDrewZA** [comment]
I do have a lot of shows registered in SR (238 to be exact), but my wanted list is only new shows, so very short, and generally empty.  I have been on a bit of a cleanup mission lately to move the ended shows out and archive them, which will about halve that number.  You reckon that's too many?  Further, my country doesn't use static ips - its all dynamic, so they would have to block entire subnets, or be using some other method.

Ive just retried their website and now its available to me, but the add shows feature is still not giving results.

A further poke around led me to a post on the kodi site which kind of suggested that people that have nfo files for series, etc would be ok after the TVDB upgrade, but those without would have issues.  I'm not nearly fluent enough to know if the same applies here or not - you will have to decide...
Take a peek:
https://forum.kodi.tv/showthread.php?tid=323588

**Comment by loungebob** [comment]
@miigotu Not IP, tried 3 very different IP ranges. Also deleted all ended shows, all nfo/images folder contents and did a complete rescan. Still no dice.

**Comment by MrSnoebel** [comment]
I did an install on the same IP on a NAS (Synology) as a test, SR is working fine then.
On the windows 2016 install the problem remains, adding with .nfo works still fine, SR does get al the details and other info from TVDB without any problems.

**Comment by kingchris1031** [comment]
I am having the same issue. I originally had my setup on OpenMediaVault which was having this issue. I now have this running on Ubuntu Server 17.10... same issue.

**Comment by MrSnoebel** [comment]
Latest master f30a84430b444bbd39308bfb8ff85ca17a48abd1  still has the issue.

**Comment by MrSnoebel** [comment]
Correct, as a minimum you need to fill in the name and the ID in de .nfo file.
Both need to match the info from TVDB.

**Comment by gurmukhp** [comment]
The ID matches and the name also matches, yet SickRage needs to do a lookup on TVDB which returns an error.

**Comment by DrDrewZA** [comment]
I did use this method and it worked for me - I think it would be easiest if you posted the contents of your text file here so we can see if we can identify any error for you.

On another note, I have been reading a  lot and have a question (as opposed to a statement, as I am not a coder, so may be off the mark):

Sickrage, as I understand it, still uses v1 of the TVDB API.  This API is outdated and not being supported anymore, even though it has been left running and available for now.  To a layman like me, this means it is a 'best effort' service and you get what you get.  Perhaps this is the cause of the erratic behaviour?  Perhaps the v2 API needs to be implemented and this may solve the problem?  I realise this is way easier said than done, and imagine it is a fairly large undertaking requiring more than just a few hours of coding by the devs, so we will need to be patient and wait it out while they get to grips with it, if they decide it is something they need/want to do.

**Comment by DrDrewZA** [comment]
I can confirm this is still an issue - @miigotu any movement here?  all parties on this thread haven't been able to add shows without using a clunky workaround since last year...  heeeelp....

**Comment by miigotu** [comment]
I cant reproduce the issue so I cant really help much

**Comment by MrSnoebel** [comment]
6e3a1dccd94857fc381c9a246b903904eca424e1 Still has the issue.

@miigotu That's strange, even when I did a fresh install I can not add any show using the function in the dropdown menu. Let me know if I can send you any info or logs to help !

**Comment by SplatmanNL** [comment]
I'm also having this same issue (also using 6e3a1dc), nothing showing up in the logfile however...
the "searching" wheel just keeps spinning but never shows results.
I really hope this can be fixed!

**Comment by avastmick** [comment]
I now get the same failures to add shows, since the most recent update (commit `6e3a1dc`). So, I've done some tests.

__TL; DR__ It looks as if [thetvdb.com](https://thetvdb.com) is blocking api requests, definitely over `http`, but possibly `https` too, but I cannot reproduce the latter. If you change __public__ IP address, the blocking goes away. So, if you have a fixed IP address, you are kinda screwed, unless you route your SR traffic through a VPN. If you are on DHCP from your ISP, you should just be able to reboot your modem and get a new IP and the issue is resolved.

__Long Version__

Previously, I have had no issues with SR, though (as I understand it), [thetvdb.com](https://thetvdb.com) is undergoing an upgrade and I was seeing connection timeouts in the logs and I was getting `503` errors when navigating via a browser. I do not think this is the issue. I will explain:

- If I try to add a show via the interface normally, I see nothing in the logs. 
- If I try to add a show using the `.info` method by @MrSnoebel , detailed above, I _do_ get an error:

```
AA tvdb_error: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/337302/en.xml
AA raise tvdb_error(e)
AA File "/home/pi/.sickrage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
AA self.config['url_seriesInfo'] % (sid, getShowInLanguage)
AA File "/home/pi/.sickrage/lib/tvdb_api/tvdb_api.py", line 841, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/home/pi/.sickrage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
AA s = t[self.indexer_id]
AA File "/home/pi/.sickrage/sickbeard/show_queue.py", line 324, in run
AA Traceback (most recent call last):
2018-03-05 09:49:16 ERROR    SHOWQUEUE-ADD :: [6e3a1dc] Unable to look up the show in /media/video/TV/Grown-up TV/Counterpart on theTVDB using ID 337302, not using the NFO. Delete .nfo and try adding manually again.: Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/337302/en.xml
2018-03-05 09:49:16 INFO     SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/home/pi/.sickrage/cache/indexers/theTVDB', u'language': u'en'}
2018-03-05 09:49:16 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /media/video/TV/Grown-up TV/Counterpart
```
However, if the URL used is manually navigated in a browser, the browser complains `Connection reset by peer`, __but__ if I change the URL to `https`, valid XML metadata for the show is returned:

```xml
<Data><Series><id>337302</id><Actors>|J. K. Simmons|Olivia Williams |Harry Lloyd|Sara Serraiocco|Nicholas Pinnock|Nazanin Boniadi|Ulrich Thomsen|</Actors><Airs_DayOfWeek>Sunday</Airs_DayOfWeek><Airs_Time>8:00 PM</Airs_Time><ContentRating>TV-MA</ContentRating><FirstAired>2017-12-10</FirstAired><Genre>|Drama|Science-Fiction|Thriller|</Genre><IMDB_ID>tt4643084</IMDB_ID><Language>en</Language><Network>Starz!</Network><NetworkID/><Overview>After discovering that the spy agency he works for is hiding a gateway to a parallel dimension, a low-level UN bureaucrat in Berlin is thrust into a shadow world of intrigue and danger and must determine if he can trust his near-identical counterpart in the other world.</Overview><Rating>8.2</Rating><RatingCount>12</RatingCount><Runtime>55</Runtime><SeriesID/><SeriesName>Counterpart</SeriesName><Status>Continuing</Status><added>2017-11-02 10:43:26</added><addedBy>489977</addedBy><banner>graphical/337302-g6.jpg</banner><fanart>fanart/original/337302-8.jpg</fanart><finale_aired>2018-03-25</finale_aired><lastupdated>1520211124</lastupdated><poster>posters/337302-4.jpg</poster><slug>counterpart</slug><tms_wanted_old>0</tms_wanted_old><zap2it_id/></Series></Data>
```

Also, if I change my public IP address (using a VPN, checking that the IP is different by searching "My IP address"), the XML metadata returns for both `http` _and_ `https` URLs. So, the hypothesis given by @miigotu looks to be correct.

Similar log entries are seen if adding shows via IMDB (adding "Counterpart"):

```
2018-03-05 10:15:48 INFO     Thread-17 :: Unable to to find tvdb ID to add Counterpart
2018-03-05 10:15:48 INFO     Thread-17 :: Request failed: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

Or via Trakt (adding "Krypton"):

```
2018-03-05 10:18:16 WARNING  Thread-15 :: Show id 328599 not found on theTVDB, not adding show: error Connection error ('Connection aborted.', error(104, 'Connection reset by peer')) while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/328599/en.xml
2018-03-05 10:18:16 INFO     Thread-15 :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/home/pi/.sickrage/cache/indexers/theTVDB', u'language': u'en'}
```

So, I suggest this is a SR issue, not due to [thetvdb.com](https://thetvdb.com) being flaky right now, but due to the fact [thetvdb.com](https://thetvdb.com) has tightened up its API. It could be it is not allowing `http` usage, but more likely, it is related to the version of the API used (someone mentioned SR uses a deprecated API version), or [thetvdb.com](https://thetvdb.com) is more aggresively preventing multiple hits from the same requestor.

**Comment by SplatmanNL** [comment]
Are you sure it's not a problem on the TVDB side? I just read their forum: 
https://forums.thetvdb.com/viewtopic.php?f=4&t=39984&hilit=sickrage&start=30
And it seems more people are suffering from the same problem (and it does not seem specifically SR-related). But to be honest, I'm not technical enough to be able to judge that....
I do hope it will be fixed soon, as I really want to add some new shows.

**Comment by avastmick** [comment]
Yes, it is a thetvdb.com issue. They are blocking certain IP addresses. The instability issues during the tvdb upgrade are not the cause of the SR add shows failures. 

But, SR uses an old API, that is no longer supported, so the proper fix maybe a big job.

**Comment by DrDrewZA** [comment]
ah damn - @avastmick you got me all excited...  Tried your fix, and it's not doing it for me, unfortunately.  The issue remains after editing that line and restarting.  Seems it is not as simple as all that.  Thanks for trying though!

**Comment by avastmick** [comment]
Yeah, I suspected that would happen, that HTTPS would be blocked too, for some. Kodi is now down for me and can't update, not sure what version of tvdb API that uses.

What I can't tell is whether this is the tvdb.com upgrade screwing, or they are actively blocking old usages of API v1, or something more nefarious, like the big DDoS attacks that are rolling about, or worse some campaign to stop usage of apps like SR, Kodi etc...

For me, SR works right now, but Kodi won't update to show the new shows... Aarrgh!!

I'm out of ideas tbh.

**Comment by MrSnoebel** [comment]
Problem is fixed with  53e6cc50c086757c31fc518b550d7681c61649e6 

Thanks for taking care !

**Comment by DrDrewZA** [comment]
Not for me it isn't...  

As an aside, I've started using this as a workaround:
http://127.0.0.1:8081/addShows/addShowByID?indexer_id=331821&show_name=the+looming+tower

I just adjust the show id and name and paste the link into my browser.  Works perfectly. Only the search function is haywire, not the add show function.  All the other methods work as well - trakt lists, etc

**Comment by miigotu** [comment]
Try the update_requests branch. This honestly is not a SR problem (unless you count that we are using the old api). However, the new libs allow it to use different ssl encryption methods so you could give it a try

**Comment by MrSnoebel** [comment]
I just installed the updates, IP did not change, it works just fine now for me.
But I did not try for several days, so maybe TVDB released my IP ?
If that was the case I would be surprised, because the TVDB function itself, getting info, banners etc did work fine, for me it was just the search that was not working.

**Comment by miigotu** [comment]
I just merged that branch to develop and deleted it, try the develop branch xD

**Comment by miigotu** [comment]
`But I did not try for several days, so maybe TVDB released my IP ?` __Very likely this is the reason it worked for you now__

**Comment by SplatmanNL** [comment]
I chose to do a clean install and rebuilt the entire database. Now it’s working fine. But that could also be because i didn’t use the update function from TVDB for several days (so maybe my IP was also released...)

**Comment by MrSnoebel** [comment]
As said, that would be strange, blocking the IP only for the serach, not for the other functions ?
But I'm no way near an expert on this matter, just a user :-)

Glad that it is working again.

The only thing I can contribute against it is that the SR install I did several weeks ago (when the windows install wasn't working) on a Synology did work just fine and that uses the same IP externally.

**Comment by miigotu** [comment]
¯\_(ツ)_/¯

**Comment by DrDrewZA** [comment]
ah crisis - please help this idiot out - I switched to dev branch in the settings, and now SR wont start - any ideas?

**Comment by miigotu** [comment]
wtf, try starting it manually I need to know asap whats wrong because I just pushed an update to master AHHH

**Comment by DrDrewZA** [comment]
nope - manually starting no good...

**Comment by miigotu** [comment]
cd to the source dir, `./SickBeard.py` and tell me what it says

**Comment by DrDrewZA** [comment]
C:\SickRage\SickRage>sickbeard.py
Traceback (most recent call last):
  File "C:\SickRage\SickRage\SickBeard.py", line 66, in <module>
    import sickbeard
  File "C:\SickRage\SickRage\sickbeard\__init__.py", line 45, in <module>
    from sickbeard.databases import mainDB, cache_db, failed_db
  File "C:\SickRage\SickRage\sickbeard\databases\mainDB.py", line 36, in <module>
    from sickbeard import subtitles
  File "C:\SickRage\SickRage\sickbeard\subtitles.py", line 53, in <module>
    provider_manager.unregister('subscenter = subliminal.providers.subscenter:SubsCenterProvider')
  File "C:\SickRage\SickRage\lib\subliminal\extensions.py", line 77, in unregister
    raise ValueError('Extension not registered')
ValueError: Extension not registered

**Comment by miigotu** [comment]
Not sure what branch you are on, or if that is even our source, because that line doesnt exist on develop or master.

Do these commands from the source dir and tell me what they output

```
cd C:\SickRage\SickRage
C:\SickRage\Git\git.exe branch
C:\SickRage\Git\git.exe status
C:\SickRage\Git\git.exe remote show origin
C:\SickRage\Git\git.exe checkout master
```

**Comment by DrDrewZA** [comment]
I tried that same thing - did a manual git reset to master and I'm back up and running...  Weird - must have failed when I switched to develop and done some weirdness...

**Comment by DrDrewZA** [comment]
While I was waiting, I used these commands as found for a manual Git reset on the FAQ's:

git remote add upstream https://github.com/SickRage/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

Sorted my problem out - no idea why it fell over when I switched to develop though...

**Comment by miigotu** [comment]
I still want to know the output of `git remote show origin` haha

**Comment by DrDrewZA** [comment]
Lol - here you go:

Push  URL: https://github.com/andrew@el.co.za/SickRage.git
  HEAD branch: master
  Remote branches:
    4369                    tracked
    custom_exception_season tracked
    develop                 tracked
    home-split              tracked
    master                  tracked
    pp-delrarcontents-fix2  tracked
    pp_adjustments          tracked
    refactor_libtrakt_api   tracked
    rewrite-libtrakt        tracked
    setup-py                tracked
    tvdb-api-v2             tracked
    tvrage                  tracked
    tvvault                 tracked
  Local branches configured for 'git pull':
    develop merges with remote develop
    master  merges with remote master
  Local refs configured for 'git push':
    develop pushes to develop (local out of date)
    master  pushes to master  (local out of date)

**Comment by miigotu** [comment]
Ok =P

**Comment by DrDrewZA** [comment]
Aaaaah *enlightenment dawns*  of course...  Done.

**Comment by loungebob** [comment]
SR stopped working last night or this morning. cant get it to start on the configured port with nssm. cant get it to start manually. uninstall and reinstall leads to a starting SR but on the default port even though I changed it in the installer and it’s correct in nssm. when SR startsbon default port after reinstall it says there is no config.ini and all values will default. replacing the files with the backup variants leads to a non-starting SR again.

I have not changed a thing, it must have been an update.

how do I get it to start with all my previous settings and db intact?

**Comment by loungebob** [comment]
nevermind, a flush made it all work again.

@miigotu any way I can check if my IP is blocked from using the tvdb api? adding new shows still the same issue as when I started the thread.

**Comment by statik1983** [comment]
Same issue after switching to Developer Branch.  I switched via General Configuration - Advanced Settings - GitHub.

**Comment by MrSnoebel** [comment]
Not sure why, but for me it is not working also again.. Did not change or update anything.
Still on 53e6cc50c086757c31fc518b550d7681c61649e6

**Comment by miigotu** [comment]
The commit and the branch have nothing to do with it. The tvdb site and the API are operated with different rules and services. The only thing we can TRY is to switch to tvdb api v2, which is a MASSIVE rewrite.

**Comment by statik1983** [comment]
OK... so TVDB updated its API, but Sickrage has not updated to reflect this change.  So then the Sickrage devs need to make the update to work with the new TVDB API.  It has to be done.  But in the meantime, they should at least add a second indexer for us to search and add shows with.  This has been an issue for months now, so why are the devs ignoring this, or are they not?  Can we get an update devs?  We should not have to rely on workarounds, unless the devs are actually working this issue and we have no secondary indexer.

**Comment by miigotu** [comment]
BOTH api versions are live on tvdb. They only block a few people who are using the api excessively, either by extra restarts, forced refreshes, or simply having hundreds of shows.  Pause old shows that are no longer airing, that will help tremendously.

**Comment by DrDrewZA** [comment]
Whoa hold on - lets just take a minute to reflect on the fact we get this for nothing...  The devs are active - commits have been coming regularly, but people have only so much spare time to spend coding on their personal projects.  So perhaps a bit of patience and understanding of reality is necessary - as has just been said its a huge job, without any guarantee it would even actually work - the tvdb limitations may be exactly the same on the v2 api, leaving us in exactly the same position as we are now. 

@miigotu - is there a  way we could reduce the frequency of our database refreshes, thereby reducing the total number of hits?  The way I understand your point is if we reduce the frequency of the daily search etc we could improve our situation?  Say from every 10 minutes, to every 30?

**Comment by statik1983** [comment]
It has been months.  You either commit to a product free or not and keep is working or it will fall through and no one will use it.

**Comment by miigotu** [comment]
@statik1983 this project is freely distributed and you have free rights to modify it however you see fit. Submit a pull request, pay me a salary, wait, or move on.

**Comment by miigotu** [comment]
@DrDrewZA it should only be refreshing shows once a day. If you pause inactive shows (ones that are canceled/discontinued/not currently airing) then they will not be in the list to be refreshed or updated.  If you do that, and NEVER manually click the show refresh/update button on the show page or mass update page I think in a few days the block/ban on your IP might fall off on TVDB's side.  I cannot say this for certain, because I have nothing to go on to even verify if it is a problem on their end and I cannot reproduce it here. Usually, tvdb (or any site who is having issues with SR) would contact me and lets me know if there is a widespread issue, but they have not contacted me.

I am planning to make a run at changing to tvdb api2, but it is a really complicated task, and several people have already tried doing it without much success yet. It was avoided so far mostly because it had introduced some serious regressions since their api v2 is not completed yet and there has been little work on completing it for about a year.  My plan is going to be a multi stage plan, including adding tvmaze, and some db upgrades (the scariest part), and then upgrading to tvdb api v2 (since with any regression there we will have tvmaze to fall back on as an indexer)

**Comment by miigotu** [comment]
@DrDrewZA Im curious if this is an issue with a specific browser? Or cross origin or some other protection in the browser you are using? Try chrome please. Also, try using SickRage in https mode and see if it changes.  Im going to add tvmaze just for show searches here in a bit (for now this will be a quick workaround), since adding by show id works I can just search shows and use the id to add the show after you select it. Easy

**Comment by loungebob** [comment]
oh crap it works in chrome. not in IE11 though.

**Comment by miigotu** [comment]
Ok, so we know the problem then, give me some time

**Comment by miigotu** [comment]
@OmgImAlexis I cant figure out why this is doing this, its failing inside `searchRequestXhr` on core.js, only on IE

**Comment by statik1983** [comment]
Works in Firefox as well.   I always used IE.

**Comment by MrSnoebel** [comment]
Not sure why, but for me it's working again, I did disable all the shows that have ended as suggested in earlier posts. I don't have a large list of series, about 25 active and now 7 paused.
Will try it every day once to see if it keeps working.

I'm a little lost with the last posts, are you guys suggesting that IE is the problem? Do you mean that IE being used by SR to goto TVDB, or the user going to SR ?

I also wanted to express my deapest respect and am very gratefull for all the work done by the devs!

**Comment by DrDrewZA** [comment]
Oh FFS.  Yep - it works like a bomb in Chrome - So IE is indeed the common point of failure.  

Frustrating that the answer is so simple - we should have tried different browsers long ago!  Thanks @miigotu I'm quite happy to switch to Chrome on this media machine of mine, but stopped using it for other purposes when they dropped NPAPI support as I needed it and wanted one browser that would do everything.

**Comment by DrDrewZA** [comment]
As an aside - to learn properly from this experience, can I suggest that the initial bug report be updated to include not only the OS the user is using but also the browser so you get that information right off the bat and perhaps can we can start seeing that pattern more easily?

**Comment by miigotu** [comment]
@MrSnoebel this bug report is about the addNewShow page. If you go to the addNewShow page and search for a show on ie8-11 you get no results. It works in chrome and firefox.

@DrDrewZA I added browser to the ISSUE_TEMPLATE in the PR for this issue

**Comment by MrSnoebel** [comment]
So, it's not anymore related to frequency gtting request to TVDB, but really a bug in the code using IE ?
But it works now, did work sometimes last weeks and works always when I have a SR install on a Synology. I only tested with IE/Edge.

Not sure if I can follow this, but happy if you guys can fix it permanently.

**Comment by miigotu** [comment]
FIXED. I will merge it to master shortly

**Comment by DrDrewZA** [comment]
Confirmed as fixed!  You da man, so they say  :-)

Thanks for taking the time @miigotu  I'm sure I speak for most participants on this thread when I say we all appreciate it!

**Comment by miigotu** [comment]
most. =P

YW

**Comment by loungebob** [comment]
yay it works now in IE11 too 👍

**Comment by miigotu** [comment]
Yeah, that bug seems to happen when a c++ dev makes a PR to javascript +1

**Comment by bolhaskutya** [comment]
Adding new shows doesn't work for me. I'm on the latest. I tried everything. Reinstalled sickbeard. Tried firefox, chrome. No luck. I get no results when adding a new show. I'm on synology.

Adding tvshow.nfo works, but afterwards the show data isn't downloaded.

Can this be related to node.js? Which version do I need? v0.1, v0.12, v4, v6, v8? I have v8 installed currently.

**Comment by bolhaskutya** [comment]
Update: Disabling ipv6 in synology network settings fixed it! :)

**Comment by nielslemmens** [comment]
I have the same issue on a Synology DS115. up to date. Disabling ipv6 helped, but this is not sustainable since my router pushes ipv6. Please fix this
